<?php

include_once('openchurch_gallery.features.inc');
include_once('openchurch_gallery.install');

/**
 * Implementation of hook_nodeapi()
 */
function openchurch_gallery_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){

  /**
   * Override gallery node detail
   */
  if ($node->type == 'openchurch_gallery' AND $op == 'load' AND arg(0) == 'node' AND ctype_digit(arg(1)) AND !arg(2)) {

    /**
     * If a ministry is associated with this gallery we are going to change the title
     * to reflect the ministry
     */
    if ($nid = $node->field_oc_ministry[0]['nid']) {
      $n = node_load($nid);

      drupal_set_title($n->title.' Photo Archives');
    }
    else
      drupal_set_title('Church Wide Photo Archives');
  }
}

/**
 * Implementation of hook_apps_app_info()
 */
function openchurch_gallery_apps_app_info() {
  return array(
    'demo content description' => 'This will populate the galleries page with a couple of sample galleries for demonstration.',
    'demo content module' => 'openchurch_gallery_demo_content',
  );
}