<?php
/**
 * @file
 * Code for the outfitter Video feature.
 */

include_once('openchurch_video.features.inc');

/**
 * Implementation of hook_apps_app_info()
 */
function openchurch_video_apps_app_info() {
  return array(
    'demo content description' => 'This will populate the video page with a couple of sample videos for demonstration.',
    'demo content module' => 'openchurch_video_demo_content',
  );
}
