api = 2
core = 7.26
projects[addressfield][version] = 1.0-beta5
projects[addressfield][subdir] = contrib
projects[backup_migrate][version] = 2.8
projects[backup_migrate][subdir] = contrib
projects[calendar][version] = 3.4
projects[calendar][subdir] = contrib
projects[cck][version] = 7.x-3.0-alpha3
projects[cck][subdir] = contrib
projects[colorbox][version] = 2.5
projects[colorbox][subdir] = contrib
projects[content_taxonomy][version] = 1.0-beta2
projects[content_taxonomy][subdir] = contrib
projects[context][version] = 3.1
projects[context][subdir] = contrib
projects[context_breadcrumb_current_page][version] = 1.0-beta2
projects[context_breadcrumb_current_page][subdir] = contrib
projects[email][version] = 1.2
projects[email][subdir] = contrib
projects[features_extra][version] = 1.0-beta1
projects[features_extra][subdir] = contrib
projects[filefield_sources][version] = 1.9
projects[filefield_sources][subdir] = contrib
projects[fitvids][version] = 1.14
projects[fitvids][subdir] = contrib
projects[fontyourface][version] = 2.8
projects[fontyourface][subdir] = contrib
projects[menu_breadcrumb][version] = 1.5
projects[menu_breadcrumb][subdir] = contrib
projects[metatag][version] = 1.0-beta8
projects[metatag][subdir] = contrib
projects[nodequeue][version] = 2.0-beta1
projects[nodequeue][subdir] = contrib
projects[pathologic][version] = 2.12
projects[pathologic][subdir] = contrib
projects[plup][version] = 1.0-alpha1
projects[plup][subdir] = contrib
projects[plupload][version] = 1.6
projects[plupload][subdir] = contrib
projects[rss_field_formatters][version] = 1.2
projects[rss_field_formatters][subdir] = contrib
projects[rules][version] = 2.6
projects[rules][subdir] = contrib
projects[sharethis][version] = 2.5
projects[sharethis][subdir] = contrib
projects[simplenews][version] = 1.1
projects[simplenews][subdir] = contrib
projects[styles][version] = 2.0-alpha8
projects[styles][subdir] = contrib
projects[superfish][version] = 1.9
projects[superfish][subdir] = contrib
projects[views_php][version] = 1.x-dev
projects[views_php][subdir] = contrib
projects[views_slideshow][version] = 3.1
projects[views_slideshow][subdir] = contrib
projects[webform][version] = 3.19
projects[webform][subdir] = contrib

; The Panopoly Foundation
projects[panopoly_core][version] = 1.1
projects[panopoly_core][subdir] = panopoly
projects[panopoly_images][version] = 1.1
projects[panopoly_images][subdir] = panopoly
projects[panopoly_theme][version] = 1.1
projects[panopoly_theme][subdir] = panopoly
projects[panopoly_magic][version] = 1.1
projects[panopoly_magic][subdir] = panopoly
projects[panopoly_widgets][version] = 1.1
projects[panopoly_widgets][subdir] = panopoly
projects[panopoly_admin][version] = 1.1
projects[panopoly_admin][subdir] = panopoly
projects[panopoly_users][version] = 1.1
projects[panopoly_users][subdir] = panopoly
; The Panopoly Toolset
projects[panopoly_pages][version] = 1.1
projects[panopoly_pages][subdir] = panopoly
projects[panopoly_wysiwyg][version] = 1.1
projects[panopoly_wysiwyg][subdir] = panopoly
projects[panopoly_search][version] = 1.1
projects[panopoly_search][subdir] = panopoly

; Libraries

;Disabling for now
;libraries[jquery.cycle][type] = "libraries"
;libraries[jquery.cycle][download][type] = "file"
;libraries[jquery.cycle][download][url] = "http://malsup.github.com/jquery.cycle.all.js"
;libraries[jquery.cycle][directory_name] = "jquery.cycle"

libraries[plupload][download][type] = "get"
libraries[plupload][download][url] = "https://github.com/jackmoore/colorbox/archive/1.x.zip"
libraries[plupload][directory_name] = "colorbox"

libraries[superfish][download][type] = "get"
libraries[superfish][download][url] = "https://github.com/mehrpadin/Superfish-for-Drupal/zipball/master"
libraries[superfish][directory_name] = "superfish"

libraries[plupload][download][type] = "get"
libraries[plupload][download][url] = "https://github.com/downloads/moxiecode/plupload/plupload_1_5_2.zip"
libraries[plupload][directory_name] = "plupload"