<?php

include_once('openchurch_podcast.features.inc');
include_once('openchurch_podcast.install');

/**
 * Implementation of hook_enable()
 */
function openchurch_podcast_enable(){
  drupal_flush_all_caches();//we need to do this before we can add content

  //only load sample content if no content is found
  if (!db_result(db_query('SELECT count(nid) FROM {node} WHERE type = "openchurch_podcast"')))
    _openchurch_podcast_load_podcast_content();//load sample content
}