<?php

include_once('openchurch_bulletin.features.inc');
include_once('openchurch_bulletin.install');

/**
 * Implementation of hook_enable()
 */
function openchurch_bulletin_enable(){
  drupal_flush_all_caches();//we need to do this before we can add content

  //only load sample content if no content is found
  if (!db_result(db_query('SELECT count(nid) FROM {node} WHERE type = "openchurch_bulletin"')))
    _openchurch_bulletin_load_bulletin_content();//load sample content
}