<?php

include_once('openchurch_blog.features.inc');
include_once('openchurch_blog.install');

/**
 * Implementation of hook_form_alter()
 */
function openchurch_blog_form_alter(&$form, &$form_state, $form_id){

  if ($form_id == 'views_exposed_form') {
    /**
     * Override openchurch blog filter
     */
    if ($form['#id'] == 'views-exposed-form-openchurch-latest-blogs-page-1') {
      $form['submit']['#value'] = 'update';
    }
  }
}

/**
 * Implementation of hook_apps_app_info()
 */
function openchurch_blog_apps_app_info() {
  return array(
    'demo content description' => 'This will populate the blogs page with a couple of sample blogs for demonstration.',
    'demo content module' => 'openchurch_blog_demo_content',
  );
}