<?php

/**
 * Implementation of hook_init() 
 */
function openchurch_video_demo_content_init(){
  
  /**
   * Run a video content fix for the first time the site loads 
   */
  if (variable_get('openchurch_video_demo_content_first_time', 1)){
    $video_fids = variable_get('openchurch_video_fids', '');

    /**
    * For upgrades 
    */
    if ($video_fids){
      foreach (array('oc_video1', 'oc_video2') as $video_machine_name){
        $nid = db_query('SELECT nid FROM {defaultcontent} WHERE name = :name', array('name' => $video_machine_name))->fetchColumn();

        if ($nid){
          foreach (array('field_data_field_oc_video', 'field_revision_field_oc_video') as $table){
            db_update($table)
              ->fields(array(
                'field_oc_video_fid' => $video_fids[$video_machine_name],
              ))
              ->condition('entity_id', $nid)
              ->execute();
          }
        }
      }
    }
        
    variable_set('openchurch_video_demo_content_first_time', 0);
  }
}