<?php
/**
 * @file
 */

/**
 * Implementation of hook_enable() 
 */
function openchurch_video_demo_content_enable(){
  
  /**
   * Add media video 
   */
  $nid = db_query('SELECT nid FROM {defaultcontent} WHERE machine_name = :machine_name', array(':machine_name' => 'oc_video1'))->fetchColumn();
  
  $node = node_load($nid);
  
  if ($nid) {
    $fid = db_query('SELECT fid FROM {file_managed} WHERE uri = :uri', array(':uri' => 'http://vimeo.com/18352872'))->fetchColumn();
    
    if (!$fid){
      $file            = new stdClass();
      $file->filename  = 'Drupal 7 Marketing Video';
      $file->status    = 1;
      $file->filemime  = 'video/vimeo';
      $file->filesize  = 0;
      $file->uid       = 1;
      $file->uri       = 'http://vimeo.com/18352872';
      $file->timestamp = time();
      $file->type      = 'video';
      drupal_write_record('file_managed', $file);
      $fid = $file->fid;
    }

    $node->field_video[LANGUAGE_NONE][0]['fid'] = $fid;

    node_save($node);
  }
  
  $nid = db_query('SELECT nid FROM {defaultcontent} WHERE machine_name = :machine_name', array(':machine_name' => 'oc_video2'))->fetchColumn();
  
  if ($nid){
    $node = node_load($nid);

    $fid = db_query('SELECT fid FROM {file_managed} WHERE uri = :uri', array(':uri' => 'http://www.youtube.com/watch?v=26_OZeBmpXs'))->fetchColumn();
    
    if (!$fid){
      $file            = new stdClass();
      $file->filename  = 'Drupal CMS Video - "What is Drupal?"';
      $file->status    = 1;
      $file->filemime  = 'video/vimeo';
      $file->filesize  = 0;
      $file->uid       = 1;
      $file->uri       = 'http://www.youtube.com/watch?v=26_OZeBmpXs';
      $file->timestamp = time();
      $file->type      = 'video';
      drupal_write_record('file_managed', $file);
      $fid = $file->fid;
    }
      
    $node->field_video[LANGUAGE_NONE][0]['fid'] = $fid;

    node_save($node);
  }
}