<?php

include_once('openchurch_events.features.inc');
include_once('openchurch_events.install');

/**
 * Implementation of hook_form_alter()
 */
function openchurch_events_form_alter(&$form, &$form_state, $form_id){

  if ($form_id == 'views_exposed_form') {
    /**
     * Override openchurch events filter
     */
    if ($form['#id'] == 'views-exposed-form-openchurch-events-default') {
      $form['submit']['#value'] = 'update';
    }
  }
}