<?php

include_once('openchurch_events.features.inc');
include_once('openchurch_events.install');

/**
 * Implementation of hook_form_alter()
 */
function openchurch_events_form_alter(&$form, &$form_state, $form_id){

  if ($form_id == 'views_exposed_form') {
    /**
     * Override openchurch events filter
     */
    if ($form['#id'] == 'views-exposed-form-openchurch-events-default') {
      $form['submit']['#value'] = 'update';
    }
  }
}

/**
 * Implementation of hook_apps_app_info()
 */
function openchurch_events_apps_app_info() {
  return array(
    'demo content description' => 'This will populate the events page with a couple of sample events for demonstration.',
    'demo content module' => 'openchurch_events_demo_content',
  );
}