<?php
$nodes = array(
  array(
    'nid' => '',
    'type' => 'openchurch_block',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'About Our Staff',
    'body' => '<p>OpenChurch\'s full time and part time staff and ministers are dedicated to serving the needs of the Church and would be happy to talk to you and help you in any way we can! Feel free to call the church and speak with our receptionist, or you may contact a staff member directly below.</p>
<p><strong>Church Office Hours</strong>: 8am - 5pm Mon-Fri<br /><strong>Phone</strong>: 615.375.0601<br /><strong>Fax</strong>: 615.373.5343</p>',
    'teaser' => '<p>OpenChurch\'s full time and part time staff and ministers are dedicated to serving the needs of the Church and would be happy to talk to you and help you in any way we can! Feel free to call the church and speak with our receptionist, or you may contact a staff member directly below.</p>
<p><strong>Church Office Hours</strong>: 8am - 5pm Mon-Fri<br /><strong>Phone</strong>: 615.375.0601<br /><strong>Fax</strong>: 615.373.5343</p>',
    'log' => 'openchurch-staff-sample-content',
    'revision_timestamp' => '1295567667',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'block/about-our-staff',
    'field_oc_machine_name' => array(
      '0' => array(
        'value' => 'about_staff',
      ),
    ),
    'field_oc_hide_title' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'taxonomy' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
  array(
    'nid' => '',
    'type' => 'openchurch_staff',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'John Doe',
    'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac libero nunc. Nunc tempor magna et lectus interdum et congue augue dictum.</p><p>Proin malesuada, lectus vel pulvinar auctor, nulla libero placerat sem, eget tincidunt tellus libero in mi..</p>',
    'teaser' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac libero nunc. Nunc tempor magna et lectus interdum et congue augue dictum.</p><p>Proin malesuada, lectus vel pulvinar auctor, nulla libero placerat sem, eget tincidunt tellus libero in mi..</p>',
    'log' => 'openchurch-staff-sample-content',
    'revision_timestamp' => '1291772588',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'about/staff/john-doe',
    'field_oc_position' => array(
      '0' => array(
        'value' => 'Ministry Assistant',
      ),
    ),
    'field_oc_email' => array(
      '0' => array(
        'email' => 'test@test.com',
      ),
    ),
    'field_oc_phone' => array(
      '0' => array(
        'value' => '(x114)',
      ),
    ),
    'field_oc_staff_type' => array(
      '0' => array(
        'value' => '16',
      ),
    ),
    'field_oc_ministry' => array(
      '0' => array(
        'nid' => '',
      ),
    ),
    'field_oc_image' => array(
      '0' => NULL,
    ),
    'taxonomy' => array(
      '4' => array(
        '16' => '16',
      ),
    ),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
  array(
    'nid' => '',
    'type' => 'openchurch_staff',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'John Smith',
    'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac libero nunc. Nunc tempor magna et lectus interdum et congue augue dictum.</p>',
    'teaser' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac libero nunc. Nunc tempor magna et lectus interdum et congue augue dictum.</p>',
    'log' => 'openchurch-staff-sample-content',
    'revision_timestamp' => '1291772566',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'about/staff/john-smith',
    'field_oc_position' => array(
      '0' => array(
        'value' => 'Ministry Assistant',
      ),
    ),
    'field_oc_email' => array(
      '0' => array(
        'email' => 'test@test.com',
      ),
    ),
    'field_oc_phone' => array(
      '0' => array(
        'value' => '(x113)',
      ),
    ),
    'field_oc_staff_type' => array(
      '0' => array(
        'value' => '18',
      ),
    ),
    'field_oc_ministry' => array(
      '0' => array(
        'nid' => '',
      ),
    ),
    'field_oc_image' => array(
      '0' => NULL,
    ),
    'taxonomy' => array(
      '4' => array(
        '18' => '18',
      ),
    ),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
);
