<?php

include_once('openchurch_giving.features.inc');
include_once('openchurch_giving.install');

/**
 * Implementation of hook_enable()
 */
function openchurch_giving_enable(){
  drupal_flush_all_caches();//we need to do this before we can add content

  //only load sample content if no content is found
  if (!db_result(db_query('SELECT count(nid) FROM {node} WHERE type = "openchurch_giving"')))
    _openchurch_giving_load_giving_content();//load sample content
}