<?php
$nodes = array(
  array(
    'nid' => '',
    'type' => 'openchurch_block',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'Upcoming Events Intro',
    'body' => '<p><a href="events/calendar"><img style="float: right; margin-left: 10px;" src="/sites/all/modules/openchurch_features/openchurch_events/images/event-calendar-icon.gif" alt="" width="189" height="66" /></a>Welcome to the OpenChurch event page. Please notice two sections. &nbsp;Below you will see events listed that are considered featured events. &nbsp;Some will have online registrations when required and others may just be listed if no registration is required. &nbsp;If you would like to look at the broader church calendar please click on the icon to the right. &nbsp;Please enjoy all that OpenChurch has to offer!</p>',
    'teaser' => '<p><a href="events/calendar"><img style="float: right; margin-left: 10px;" src="/sites/all/modules/openchurch_features/openchurch_events/images/event-calendar-icon.gif" alt="" width="189" height="66" /></a>Welcome to the OpenChurch event page. Please notice two sections. &nbsp;Below you will see events listed that are considered featured events. &nbsp;Some will have online registrations when required and others may just be listed if no registration is required. &nbsp;If you would like to look at the broader church calendar please click on the icon to the right.',
    'log' => 'openchurch-events-sample-content',
    'revision_timestamp' => '1295492258',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'block/upcoming-events-intro',
    'field_oc_machine_name' => array(
      '0' => array(
        'value' => 'upcoming_events_intro',
      ),
    ),
    'field_oc_hide_title' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'taxonomy' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
  array(
    'nid' => '',
    'type' => 'openchurch_event',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'Dinner at Bethlehem',
    'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut facilisis dictum ligula ac dapibus. Nulla dictum varius quam, id rutrum lorem malesuada a. Morbi et velit urna. Morbi vestibulum dui ac ipsum pretium commodo. Donec tristique accumsan iaculis. Nam risus est, gravida ut tempor ut, dapibus sed justo.</p><p>In hac habitasse platea dictumst. Etiam viverra nisi ut eros dictum ut blandit purus pretium. Phasellus faucibus aliquet auctor. Cras posuere lacus bibendum felis adipiscing quis consectetur turpis egestas. Nam mauris enim, rhoncus non gravida eget, lobortis sed ipsum. Ut orci felis, semper sed molestie vitae, sollicitudin id ipsum. Ut in nibh tellus, eu placerat leo.</p>',
    'teaser' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut facilisis dictum ligula ac dapibus. Nulla dictum varius quam, id rutrum lorem malesuada a. Morbi et velit urna. Morbi vestibulum dui ac ipsum pretium commodo. Donec tristique accumsan iaculis. Nam risus est, gravida ut tempor ut, dapibus sed justo.</p>',
    'log' => 'openchurch-events-sample-content',
    'revision_timestamp' => '1291771643',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'events/dinneratbethlehem',
    'field_oc_ministry' => array(
      '0' => array(
        'nid' => '',
      ),
    ),
    'field_oc_url' => array(
      '0' => array(
        'url' => 'http://www.google.com',
        'title' => NULL,
        'attributes' => array(),
      ),
    ),
    'field_oc_cost' => array(
      '0' => array(
        'value' => '$8.00 - Per Attendee',
      ),
    ),
    'field_oc_dates' => array(
      '0' => array(
        'value' => '2015-12-16T06:00:00',
        'value2' => '2015-12-16T06:00:00',
        'timezone' => 'America/Chicago',
        'timezone_db' => 'UTC',
        'date_type' => 'date',
      ),
    ),
    'field_oc_location' => array(
      '0' => array(
        'lid' => '',
        'name' => '',
        'street' => '',
        'additional' => '',
        'city' => 'Cleveland',
        'province' => 'OH',
        'postal_code' => '37027',
        'country' => 'us',
        'latitude' => '0.000000',
        'longitude' => '0.000000',
        'source' => '0',
        'is_primary' => '0',
        'province_name' => 'Ohio',
        'country_name' => 'United States',
      ),
    ),
    'field_oc_downloads' => array(
      '0' => array(
        'fid' => '126',
        'uid' => '1',
        'filename' => 'test pdf.pdf',
        'filepath' => 'sites/default/files/test_pdf.pdf',
        'filemime' => 'application/pdf',
        'filesize' => '5935',
        'status' => '1',
        'timestamp' => '1291174048',
        'list' => '1',
        'data' => FALSE,
      ),
    ),
    'taxonomy' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
  array(
    'nid' => '',
    'type' => 'openchurch_event',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'Scream Free Parenting',
    'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut facilisis dictum ligula ac dapibus. Nulla dictum varius quam, id rutrum lorem malesuada a. Morbi et velit urna.</p><p>Morbi vestibulum dui ac ipsum pretium commodo. Donec tristique accumsan iaculis. Nam risus est, gravida ut tempor ut, dapibus sed justo. In hac habitasse platea dictumst. Etiam viverra nisi ut eros dictum ut blandit purus pretium. Phasellus faucibus aliquet auctor. Cras posuere lacus bibendum felis adipiscing quis consectetur turpis egestas. Nam mauris enim, rhoncus non gravida eget, lobortis sed ipsum. Ut orci felis, semper sed molestie vitae, sollicitudin id ipsum. Ut in nibh tellus, eu placerat leo.</p>',
    'teaser' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut facilisis dictum ligula ac dapibus. Nulla dictum varius quam, id rutrum lorem malesuada a. Morbi et velit urna.</p>',
    'log' => 'openchurch-events-sample-content',
    'revision_timestamp' => '1291771618',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'events/scream-free-parenting',
    'field_oc_ministry' => array(
      '0' => array(
        'nid' => '',
      ),
    ),
    'field_oc_url' => array(
      '0' => array(
        'url' => 'http://google.com',
        'title' => NULL,
        'attributes' => array(),
      ),
    ),
    'field_oc_cost' => array(
      '0' => array(
        'value' => 'FREE',
      ),
    ),
    'field_oc_dates' => array(
      '0' => array(
        'value' => '2015-12-30T06:00:00',
        'value2' => '2015-12-30T06:00:00',
        'timezone' => 'America/Chicago',
        'timezone_db' => 'UTC',
        'date_type' => 'date',
      ),
    ),
    'field_oc_location' => array(
      '0' => array(
        'lid' => '',
        'name' => '',
        'street' => '1949 Old Hickory Blvd.',
        'additional' => '',
        'city' => 'Dallas',
        'province' => 'TX',
        'postal_code' => '75081',
        'country' => 'us',
        'latitude' => '0.000000',
        'longitude' => '0.000000',
        'source' => '0',
        'is_primary' => '0',
        'province_name' => 'Texas',
        'country_name' => 'United States',
      ),
    ),
    'field_oc_downloads' => array(
      '0' => array(
        'fid' => '141',
        'uid' => '1',
        'filename' => 'test pdf.pdf',
        'filepath' => 'sites/default/files/test_pdf.pdf',
        'filemime' => 'application/pdf',
        'filesize' => '5935',
        'status' => '1',
        'timestamp' => '1291340432',
        'list' => '1',
        'data' => FALSE,
      ),
    ),
    'taxonomy' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
);
