<?php $nodes = array(
  array(
    'nid' => '',
    'type' => 'openchurch_block',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'Connect With Ministries Intro Block',
    'body' => '<h3>Boldly Announce Your Ministries and Missions Through Open Church</h3>
<p>Open Church is a platform to help you spread the word about your ministries and the ongoing efforts to make a difference. &nbsp;We would use this area to tell others about the overall mission of your church and how and where your ministries are headed. &nbsp;</p>
<p>Spread the word through the use of the internet where you can keep everyone informed of all the activities, needs, and events. &nbsp;Now with open church you don\'t have to have a full time web staff to spread the word, you can start for free, and the add features as you grow. &nbsp;If your church grows to a point you want more customization or features we\'re here to help either directly or by connecting you with one of our approved partners. &nbsp;&nbsp;</p>',
    'teaser' => '<h3>Boldly Announce Your Ministries and Missions Through Open Church</h3>
<p>Open Church is a platform to help you spread the word about your ministries and the ongoing efforts to make a difference. &nbsp;We would use this area to tell others about the overall mission of your church and how and where your ministries are headed. &nbsp;</p>',
    'log' => 'openchurch-ministry-sample-content',
    'revision_timestamp' => '1295130563',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'block/connect-ministries-intro-block',
    'field_oc_machine_name' => array(
      '0' => array(
        'value' => 'connect_ministries',
      ),
    ),
    'field_oc_hide_title' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'taxonomy' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
  array(
    'nid' => '',
    'type' => 'openchurch_ministry',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'Youth Ministry',
    'body' => '<p>Welcome to the Youth Ministry - A Sample Ministry Page of Open Church</p>
<p>Open Church allows each ministry to have their own page where the ministry can share the ideas and activities.</p>
<p>Here you see that you can upload an associated header image that is unique to the specific ministry.  A fun feature that can be updated as the year goes on to keep your church site looking fresh.</p>
<p>You can even upload associated files with this ministry where they will be kept in a centralized location that is relevant to the ministry.</p>
<p>It doesn\'t end there.  When your ministry has an event that you want to let people know about you can add an event page where people can find all the details of the event, and even register online if you so desire.  At open church we provide you with a great open platform that can grow with you as your ministry grows.</p>',
    'teaser' => '<p>Welcome to the Youth Ministry - A Sample Ministry Page of Open Church</p>
<p>Open Church allows each ministry to have their own page where the ministry can share the ideas and activities.</p>
<p>Here you see that you can upload an associated header image that is unique to the specific ministry.  A fun feature that can be updated as the year goes on to keep your church site looking fresh.</p>
<p>You can even upload associated files with this ministry where they will be kept in a centralized location that is relevant to the ministry.</p>',
    'log' => 'openchurch-ministry-sample-content',
    'revision_timestamp' => '1291823604',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'ministry/youth-ministry',
    'field_oc_thumb' => array(
      '0' => NULL,
    ),
    'field_oc_image' => array(
      '0' => array(
        'fid' => '146',
        'uid' => '1',
        'filename' => 'SWT1021.jpg',
        'filepath' => 'sites/default/files/youth_ministry_banner.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '46420',
        'status' => '1',
        'timestamp' => '1291422666',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_oc_downloads' => array(
      '0' => array(
        'fid' => '145',
        'uid' => '1',
        'filename' => 'test pdf.pdf',
        'filepath' => 'sites/default/files/test_pdf.pdf',
        'filemime' => 'application/pdf',
        'filesize' => '5935',
        'status' => '1',
        'timestamp' => '1291422316',
        'list' => '1',
        'data' => FALSE,
      ),
    ),
    'taxonomy' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => 'Youth Ministry',
      'mlid' => 0,
      'plid' => '4771',
      'menu_name' => 'primary-links',
      'weight' => '14',
      'options' => array(),
      'module' => 'menu',
      'expanded' => '0',
      'hidden' => '0',
      'has_children' => '0',
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
  array(
    'nid' => '',
    'type' => 'openchurch_ministry',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'Singles Ministry',
    'body' => '<p>Welcome to the Singles Ministry - A Sample Ministry Page of Open Church</p>
<p>Open Church allows each ministry to have their own page where the ministry can share the ideas and activities.</p>
<p>You can even upload associated files with this ministry where they will be kept in a centralized location that is relevant to the ministry.</p>
<p>It doesn\'t end there. &nbsp;When your ministry has an event that you want to let people know about you can add an event page where people can find all the details of the event, and even register online if you so desire. &nbsp;At open church we provide you with a great open platform that can grow with you as your ministry grows. &nbsp;</p>',
    'teaser' => '<p>Welcome to the Singles Ministry - A Sample Ministry Page of Open Church</p>
<p>Open Church allows each ministry to have their own page where the ministry can share the ideas and activities.</p>
<p>You can even upload associated files with this ministry where they will be kept in a centralized location that is relevant to the ministry.</p>',
    'log' => 'openchurch-ministry-sample-content',
    'revision_timestamp' => '1291775833',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'ministry/singles-ministry',
    'field_oc_thumb' => array(
      '0' => NULL,
    ),
    'field_oc_image' => array(
      '0' => NULL,
    ),
    'field_oc_downloads' => array(
      '0' => array(
        'fid' => '128',
        'uid' => '1',
        'filename' => 'test pdf.pdf',
        'filepath' => 'sites/default/files/test_pdf.pdf',
        'filemime' => 'application/pdf',
        'filesize' => '5935',
        'status' => '1',
        'timestamp' => '1291174354',
        'list' => '1',
        'data' => FALSE,
      ),
    ),
    'taxonomy' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => 'Singles Ministry',
      'mlid' => 0,
      'plid' => '4771',
      'menu_name' => 'primary-links',
      'weight' => '15',
      'options' => array(),
      'module' => 'menu',
      'expanded' => '0',
      'hidden' => '0',
      'has_children' => '0',
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
);