<?php

include_once('openchurch_blog.features.inc');
include_once('openchurch_blog.install');

/**
 * Implementation of hook_form_alter()
 */
function openchurch_blog_form_alter(&$form, &$form_state, $form_id){

  if ($form_id == 'views_exposed_form') {
    /**
     * Override openchurch blog filter
     */
    if ($form['#id'] == 'views-exposed-form-openchurch-latest-blogs-block-1') {
      $form['submit']['#value'] = 'update';
    }
  }
}

/**
 * Implementation of hook_enable()
 */
function openchurch_blog_enable(){
  drupal_flush_all_caches();//we need to do this before we can add content

  //only load sample content if no content is found
  if (!db_result(db_query('SELECT count(nid) FROM {node} WHERE type = "openchurch_blog"')))
    _openchurch_blog_load_blog_content();//load sample content
}