<?php

include_once('openchurch_blog.features.inc');
include_once('openchurch_blog.install');

/**
 * Implementation of hook_form_alter()
 */
function openchurch_blog_form_alter(&$form, &$form_state, $form_id){

  if ($form_id == 'views_exposed_form') {
    /**
     * Override openchurch blog filter
     */
    if ($form['#id'] == 'views-exposed-form-openchurch-latest-blogs-page-1') {
      $form['submit']['#value'] = 'update';
    }
  }
}