<?php
/**
 * @file
 * Code for the outfitter Video feature.
 */

include_once('openchurch_video.features.inc');

/**
 * Implementation of hook_init()
 */
function openchurch_video_init(){
  drupal_add_css(drupal_get_path('module', 'openchurch_video').'/css/openchurch_video.css');
}

/**
 * Implementation of hook_enable()
 */
function openchurch_video_enable(){
  /**
   * Vimeo Settings
   */
  db_query('DELETE FROM {file_display} WHERE name = :name', array(':name' => 'video__default__media_vimeo_video'));

  $display = array (
    'status' => 1,//enabled video player
    'weight' => 0,
    'settings' => array (
      'width' => 640,
      'height' => 480,
      'autoplay' => 0
    ),
    'name' => 'video__default__media_vimeo_video',
    'table' => 'file_display',
    'type' => 'Local',
    'export_type' => EXPORT_IN_DATABASE,
  );

  drupal_write_record('file_display', $display);

  db_query('DELETE FROM {file_display} WHERE name = :name', array(':name' => 'video__media_preview__media_vimeo_image'));

  $display = array(
    'status' => 1,
    'weight' => 2,
    'settings' => array(
      'image_style' => 'medium',
    ),
    'name' => 'video__media_preview__media_vimeo_image',
    'table' => 'file_display',
    'type' => 'Local',
    'export_type' => EXPORT_IN_DATABASE
  );

  drupal_write_record('file_display', $display);
  
  db_query('DELETE FROM {file_display} WHERE name = :name', array(':name' => 'video__media_small__media_vimeo_image'));

  $display = array(
    'status' => 1,
    'weight' => 2,
    'settings' => array(
      'image_style' => 'thumbnail',
    ),
    'name' => 'video__media_small__media_vimeo_image',
    'table' => 'file_display',
    'type' => 'Local',
    'export_type' => EXPORT_IN_DATABASE
  );

  drupal_write_record('file_display', $display);
  
  db_query('DELETE FROM {file_display} WHERE name = :name', array(':name' => 'video__media_large__media_vimeo_image'));

  $display = array(
    'status' => 1,
    'weight' => 2,
    'settings' => array(
      'image_style' => 'large',
    ),
    'name' => 'video__media_large__media_vimeo_image',
    'table' => 'file_display',
    'type' => 'Local',
    'export_type' => EXPORT_IN_DATABASE
  );

  drupal_write_record('file_display', $display);


  /**
   * Youtube Settings
   */
  db_query('DELETE FROM {file_display} WHERE name = :name', array(':name' => 'video__default__media_youtube_video'));

  $display = array (
    'status' => 1,//enabled video player
    'weight' => 0,
    'settings' => array (
      'width' => 640,
      'height' => 480,
      'autoplay' => 0
    ),
    'name' => 'video__default__media_youtube_video',
    'table' => 'file_display',
    'type' => 'Local',
    'export_type' => EXPORT_IN_DATABASE,
  );

  drupal_write_record('file_display', $display);

  db_query('DELETE FROM {file_display} WHERE name = :name', array(':name' => 'video__media_preview__media_youtube_image'));

  $display = array(
    'status' => 1,
    'weight' => 2,
    'settings' => array(
      'image_style' => 'medium',
    ),
    'name' => 'video__media_preview__media_youtube_image',
    'table' => 'file_display',
    'type' => 'Local',
    'export_type' => EXPORT_IN_DATABASE
  );

  drupal_write_record('file_display', $display);
  
  db_query('DELETE FROM {file_display} WHERE name = :name', array(':name' => 'video__media_small__media_youtube_image'));

  $display = array(
    'status' => 1,
    'weight' => 2,
    'settings' => array(
      'image_style' => 'thumbnail',
    ),
    'name' => 'video__media_small__media_youtube_image',
    'table' => 'file_display',
    'type' => 'Local',
    'export_type' => EXPORT_IN_DATABASE
  );
  
  db_query('DELETE FROM {file_display} WHERE name = :name', array(':name' => 'video__media_large__media_youtube_image'));

  $display = array(
    'status' => 1,
    'weight' => 2,
    'settings' => array(
      'image_style' => 'large',
    ),
    'name' => 'video__media_large__media_youtube_image',
    'table' => 'file_display',
    'type' => 'Local',
    'export_type' => EXPORT_IN_DATABASE
  );

  drupal_write_record('file_display', $display);
}
