<?php
$nodes = array(
  array(
    'nid' => '',
    'type' => 'openchurch_block',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'Children\'s Church',
    'body' => '<p style="text-align: right;"><img src="/sites/all/modules/openchurch_features/openchurch_homepage_rotator/images/childrens_church.jpg" alt="" width="220" height="110" /></p>',
    'teaser' => '<p style="text-align: right;"><img src="/sites/all/modules/openchurch_features/openchurch_homepage_rotator/images/childrens_church.jpg" alt="" width="220" height="110" /></p>',
    'log' => 'openchurch-homepage-rotator-sample-content',
    'revision_timestamp' => '1295315911',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'block/childrens-church',
    'field_oc_machine_name' => array(
      '0' => array(
        'value' => 'home_panel_block3',
      ),
    ),
    'field_oc_hide_title' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'taxonomy' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
  array(
    'nid' => '',
    'type' => 'openchurch_block',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'Food Pantry',
    'body' => '<p><img src="/sites/all/modules/openchurch_features/openchurch_homepage_rotator/images/food_pantry.jpg" alt="" width="220" height="110" /></p>',
    'teaser' => '<p><img src="/sites/all/modules/openchurch_features/openchurch_homepage_rotator/images/food_pantry.jpg" alt="" width="220" height="110" /></p>',
    'log' => 'openchurch-homepage-rotator-sample-content',
    'revision_timestamp' => '1295315895',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'block/food-pantry',
    'field_oc_machine_name' => array(
      '0' => array(
        'value' => 'home_panel_block2',
      ),
    ),
    'field_oc_hide_title' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'taxonomy' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
  array(
    'nid' => '',
    'type' => 'openchurch_block',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'Winter Sermons',
    'body' => '<p><img src="/sites/all/modules/openchurch_features/openchurch_homepage_rotator/images/winter_sermons.jpg" alt="" width="220" height="110" /></p>',
    'teaser' => '<p><img src="/sites/all/modules/openchurch_features/openchurch_homepage_rotator/images/winter_sermons.jpg" alt="" width="220" height="110" /></p>',
    'log' => 'openchurch-homepage-rotator-sample-content',
    'revision_timestamp' => '1295315880',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'block/winter-sermons',
    'field_oc_machine_name' => array(
      '0' => array(
        'value' => 'home_panel_block1',
      ),
    ),
    'field_oc_hide_title' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'taxonomy' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
);
