<?php
$nodes = array(
  array(
    'nid' => '',
    'type' => 'openchurch_homepage_rotator',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'The power of love',
    'body' => '',
    'teaser' => '',
    'log' => 'openchurch-homepage-rotator-sample-content',
    'revision_timestamp' => '1292777088',
    'format' => '0',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'rotator/power-of-love',
    'field_oc_image' => array(
      '0' => array(
        'fid' => '158',
        'uid' => '1',
        'filename' => 'homepage_image.jpg',
        'filepath' => 'sites/default/files/homepage_image.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '351270',
        'status' => '1',
        'timestamp' => '1292777088',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_oc_link' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'taxonomy' => array(),
    'files' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
  array(
    'nid' => '',
    'type' => 'openchurch_homepage_rotator',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'Autumn Is Here!',
    'body' => '',
    'teaser' => '',
    'log' => 'openchurch-homepage-rotator-sample-content',
    'revision_timestamp' => '1292026562',
    'format' => '0',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'rotator/autumn-is-here',
    'field_oc_image' => array(
      '0' => array(
        'fid' => '151',
        'uid' => '1',
        'filename' => 'autumn_hero.jpg',
        'filepath' => 'sites/default/files/autumn_hero.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '91149',
        'status' => '1',
        'timestamp' => '1292026561',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_oc_link' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'taxonomy' => array(),
    'files' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
);
