<?php
$nodes = array(
  array(
    'nid' => '',
    'type' => 'openchurch_block',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'Special Needs Giving',
    'body' => '<p>Occasionally, opportunities arise for our body to give to individual causes that will help our community, missions abroad, and many other causes. In addition to our standard online giving system, you may use this site to give specifically to any of the following causes:</p>',
    'teaser' => '<p>Occasionally, opportunities arise for our body to give to individual causes that will help our community, missions abroad, and many other causes. In addition to our standard online giving system, you may use this site to give specifically to any of the following causes:</p>',
    'log' => 'openchurch-giving-sample-content',
    'revision_timestamp' => '1295490527',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'block/special-needs-giving',
    'field_oc_machine_name' => array(
      '0' => array(
        'value' => 'giving_block2',
      ),
    ),
    'field_oc_hide_title' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'taxonomy' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
  array(
    'nid' => '',
    'type' => 'openchurch_block',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'Introduction to Online Giving',
    'body' => '<p>At OpenChurch we realize that many of you handle all your family finances via the internet. We are glad to announce we now have a way for you to manage your giving through our online giving platform.</p>
<p>By giving online you can give one time donations to specific causes or ministries, setup recurring monthly donations, and view a detailed history at any point you desire. All of your information is held strictly confidential. Even though you will have the opportunity to log in and print transaction histories at any point you prefer, our system is linked with our accounting so you will still get an end of year letter with your giving history.</p>',
    'teaser' => '<p>At OpenChurch we realize that many of you handle all your family finances via the internet. We are glad to announce we now have a way for you to manage your giving through our online giving platform.</p>',
    'log' => 'openchurch-giving-sample-content',
    'revision_timestamp' => '1295490521',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'block/introduction-online-giving',
    'field_oc_machine_name' => array(
      '0' => array(
        'value' => 'giving_block1',
      ),
    ),
    'field_oc_hide_title' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'taxonomy' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
  array(
    'nid' => '',
    'type' => 'openchurch_charity',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '',
    'changed' => '',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '',
    'revision_uid' => '1',
    'title' => 'Support our Food Pantry',
    'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut facilisis dictum ligula ac dapibus. Nulla dictum varius quam, id rutrum lorem malesuada a. Morbi et velit urna. Morbi vestibulum dui ac ipsum pretium commodo. Donec tristique accumsan iaculis. Nam risus est, gravida ut tempor ut, dapibus sed justo. In hac habitasse platea dictumst. Etiam viverra nisi ut eros dictum ut blandit purus pretium. Phasellus faucibus aliquet auctor. Cras posuere lacus bibendum felis adipiscing quis consectetur turpis egestas. Nam mauris enim, rhoncus non gravida eget, lobortis sed ipsum. Ut orci felis, semper sed molestie vitae, sollicitudin id ipsum. Ut in nibh tellus, eu placerat leo.</p>
<p>Fusce ac elit diam, lobortis semper magna. Duis pulvinar, purus eu porttitor interdum, sem tortor molestie justo, sed porttitor tortor ligula in quam. Fusce non convallis lectus. Aenean eleifend quam quis metus hendrerit ut pellentesque sem ultrices. Aliquam neque velit, ultricies vitae dignissim nec, feugiat sed augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis nibh ullamcorper turpis aliquet sed blandit lacus dictum. Morbi at lectus erat. Aliquam erat volutpat. Praesent ut enim aliquet odio venenatis vulputate. Mauris pellentesque mollis luctus. Vestibulum tempor diam ac sem fringilla varius.</p>
<p>Donec ac est massa. Etiam cursus, justo sed bibendum tincidunt, diam leo faucibus est, sed egestas justo nisi sed tellus. Donec vitae tellus velit, ac pellentesque sem. Suspendisse vehicula ultricies augue, at lacinia orci ultrices vel. Nam fringilla eros ac odio pellentesque et convallis tortor cursus. Vivamus vel eros in dui mattis sollicitudin. Curabitur gravida porta justo, in dignissim tortor mattis venenatis. Aenean sit amet purus urna. Integer elementum eleifend justo, sed suscipit urna molestie eu. Suspendisse iaculis sagittis convallis. Maecenas dapibus arcu purus, vitae ultrices odio. Donec interdum tincidunt libero, commodo vehicula dolor pharetra quis. Cras ullamcorper ultrices lectus, a gravida erat commodo adipiscing. Donec nec blandit tortor. In congue dignissim erat eu aliquam.</p>',
    'teaser' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut facilisis dictum ligula ac dapibus. Nulla dictum varius quam, id rutrum lorem malesuada a. Morbi et velit urna. Morbi vestibulum dui ac ipsum pretium commodo. Donec tristique accumsan iaculis. Nam risus est, gravida ut tempor ut, dapibus sed justo. In hac habitasse platea dictumst. Etiam viverra nisi ut eros dictum ut blandit purus pretium. Phasellus faucibus aliquet auctor. Cras posuere lacus bibendum felis adipiscing quis consectetur turpis egestas. Nam mauris enim, rhoncus non gravida eget, lobortis sed ipsum.',
    'log' => 'openchurch-giving-sample-content',
    'revision_timestamp' => '1292080989',
    'format' => '2',
    'name' => '',
    'picture' => '',
    'data' => 'a:1:{s:13:"form_build_id";s:37:"form-e32f0e51f01127676790d9a9de38276f";}',
    'path' => 'charity/support-our-food-pantry',
    'field_oc_image' => array(
      '0' => array(
        'fid' => '157',
        'uid' => '1',
        'filename' => 'food_pantry.jpg',
        'filepath' => 'sites/default/files/food_pantry.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '8626',
        'status' => '1',
        'timestamp' => '1292080989',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'taxonomy' => array(),
    'nodewords' => array(
      'metatags' => array(),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
);
