<?php

include_once('openchurch_homepage_rotator.features.inc');
include_once('openchurch_homepage_rotator.install');

/**
 * Implementation of hook_preprocess_page()
 */
function openchurch_homepage_rotator_preprocess_page($vars){

  //We are going to hide the title on the homepage
  if (drupal_is_front_page())
    unset($vars['title']);
}

/**
 * Implementation of hook_enable()
 */
function openchurch_homepage_rotator_enable(){
  drupal_flush_all_caches();//we need to do this before we can add content

  //only load sample content if no content is found
  if (!db_result(db_query('SELECT count(nid) FROM {node} WHERE type = "openchurch_homepage_rotator"'))) {
    _openchurch_homepage_rotator_load_rotator_content();//load sample content
    _openchurch_homepage_rotator_load_panel_content();//load sample content
  }
}