<?php
/**
 * @file
 * openchurch_homepage_rotator.features.metatag.inc
 */

/**
 * Implements hook_metatag_export_default().
 */
function openchurch_homepage_rotator_metatag_export_default() {
  $config = array();

  // Exported Metatag config instance: global:frontpage.
  $config['global:frontpage'] = array(
    'instance' => 'global:frontpage',
    'config' => array(
      'title' => array(
        'value' => '[site:name] | Welcome',
      ),
      'canonical' => array(
        'value' => '[site:url]',
      ),
      'shortlink' => array(
        'value' => '[site:url]',
      ),
    ),
  );

  return $config;
}
